### ISSUE TITLE
Double Rolls when requesting (SFRPG)

### ISSUE THREAD

**Issue by agentnos** [ironmonk88/monks-tokenbar#105]
When requesting a roll in Starfinder (unsure if in other systems), after the player clicks in the chat card to roll, the result shows up in the Tokenbar chat card, but also in a new chat card. This also causes Dice So Nice to roll twice (but as the same result)
![image](https://user-images.githubusercontent.com/6649313/122114403-24192a80-ce1b-11eb-9260-d9064200eaf0.png)

**Comment by RobTheDM** [comment]
Can confirm it's happening in Pathfinder 1e as well.

**Comment by ironmonk88** [comment]
Something changes with 0.8.x and it's made it more difficult to catch that Chat Message.  And since the Chat Message fires, Dice so Nice gets triggered.
I was going to attempt to find a way around it but decided that the best course of action would probably just be to modify the systems and let them reject the Chat Message (DnD 5e already does this so I feel it's in line with how things are going).
To that end, I have merge requests for both Starfinder and PF1 sitting pending approval.  Once that's done it'll make life a lot easier and this issue should be fixed.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
If the second chat message appears, you might need to update your system.  If it still appears, let me know.  And I'll check on it, but the code is in place, just waiting for updates in the system.
