### ISSUE TITLE
Lootables isn't removing spells.

### ISSUE THREAD

**Issue by ironmonk88** [ironmonk88/monks-tokenbar#125]

**Comment by shadydeath** [comment]
![afbeelding](https://user-images.githubusercontent.com/705408/126191770-b820816a-14ed-4582-922d-2f3de8298fae.png)
Left side is post "convert to Lootable"
Right side is original pre-conversion

Other issue semi? related. The revert button doens't always put the spells that were removed back 
![afbeelding](https://user-images.githubusercontent.com/705408/126192019-f33fa694-009f-4eae-913e-caa0e309da46.png)

Actor export incase useful: (renames from json to txt due to git refusing to upload otherwise)
[fvtt-Actor-master-of-souls.txt](https://github.com/ironmonk88/monks-tokenbar/files/6842418/fvtt-Actor-master-of-souls.txt)

**Comment by ironmonk88** [comment]
Going through the json (Thank you for that) it looks like the spells that aren't being removed are listed as weapons, and not spells.
That would explain why they aren't being removed.

I'm not sure why they aren't being added back, but it's not always an exact science with the lootables.  It can be a bit sensitive.  If you can find a way to reproduce the issue consistently, let me know.

Closing the issue because the original problem has been identified... but please re-open with information on the spells not being added back.
