### ISSUE TITLE
RequestRoll API call: Always renders chat card 

### ISSUE THREAD

**Issue by NiclasLiebhauser** [ironmonk88/monks-tokenbar#141]
While playing around with `requestRoll` from this module, I noticed this while using the button directly on the bar. One can request `blind GM rolls` which the players will not see. (Also there seems no functionality for automatically rolling this check from the roll builder window, which would be equivalent to the `fastForward ` option, just saying, this is not my main problem).

But if I trigger the `requestRoll` from anywhere else (macro or active tile trigger, which I assume are the same) even when the `rollmode` is `blindroll` a suspicious chat card will still be rendered for the player.

![image](https://user-images.githubusercontent.com/3661710/129122702-ce885cb1-cbe9-4e1a-a183-5c0fd27db50a.png)

Did I do something wrong or is this actually a bug/feature of the API?

**Comment by ironmonk88** [comment]
That's how it's written.
The roll mode is slightly different:
Public means everyone can see everyone and their rolls.
Private means everyone can see anyone that's part of the roll, but only see their own rolls.
Blind means the player can only see themselves, but not their roll.
Self means only the GM sees it.

Private is meant for those times when the players know what they're rolling, but not the result.
Blind is meant for those times when you want the player to roll, but revealing who else is rolling could reveal information.  Or when you don't want the result to be revealed to the player.
And Self is for those times that the player doesn't even know they're rolling something.

I didn't include a fastForward option on the builder window because the chat card had a "Roll All button".  Which adds the extra functionality of being able to roll all with Advantage or Disadvantage when clicking, that would get messy if added to the builder window.

**Comment by ironmonk88** [comment]
Closing this as I think it was a misconception on how the module works.
