### ISSUE TITLE
Not all of my PCs are being detected

### ISSUE THREAD

**Issue by ssveter1** [ironmonk88/monks-tokenbar#161]
Not all of my PCs are being detected or is 6 the limit?

**Comment by ironmonk88** [comment]
Make sure that your PCs are set to a friendly disposition, and that the token is owned by a player.
And if that doesn't work then you can manually include them in the token config dialog.
But there isn't a limit to how many are added, so I suspect it's one of those conditions that is preventing your tokens from being detected.

If you want to check and see what the tokenbar is considering, then type `game.MonksTokenBar.debugEnabled = 2` into the console and switch to a scene the tokens are on.  That should list all the tokens and why they were rejected.  results are [token, end result, has a player owner, can view that token, can display that token, include state].

Closing this only because there's not a lot to do if there isn't an error.
