### ISSUE TITLE
Variable target of contested check in macro

### ISSUE THREAD

**Issue by TravisWise-SW** [ironmonk88/monks-tokenbar#252]
Hello,

I am rather new at this, so this might be a bug or might be me doing something unintended, but I am trying to create a macro to handle a character ability which is resolved by a contested skill check.

I'd like the macro to always have player A be the initiator but have the defender be whomever is currently targeted.

The problem is I can't figure out what to put for the defender to refer to the currently targeted actor.

This works and gives me the correct actor to defend:
game.MonksTokenBar.requestContestedRoll({token:'PlayerA', request:'skill:per'},{token:'@target', request:'skill:ins'},{silent:true, fastForward:true, rollMode:'roll'})

But it ignores the skill: insight part and just rolls it as a straight strength check for the defender. PlayerA rolls the appropriate skill though.

If I hardcode the defenders token name back in then it uses the insight skill as expected.

Is this not a feature, or am I doing it wrong, or is it broken?

**Comment by thatlonelybugbear** [comment]
If you don't mind me jumping in, you could use something like `let target = game.user.targets.first()` to get the Token5e of the target if there is only 1 selected (at least for the 5e system).

**Comment by TravisWise-SW** [comment]
Ahh, thank you!

**Comment by ironmonk88** [comment]
That is a bug though.  It shouldn't be erasing the skill check.
It has been fixed, but, technically the only reason `@target` was working was because Tokenbar automatically selects the targeted creature as the second token if it can't figure out what you were trying to target.  So you could have put `blah` in that field and it would have worked.
Technically adding `null` (without quotes) for the second token is the preferred way to do it.  And with the next patch it will preserve the skill check.

**Comment by TravisWise-SW** [comment]
Thanks for helping me think I'm not crazy after all.
