### ISSUE TITLE
[BUG] Stats break if a resource at 0 (dnd5e)

### ISSUE THREAD

**Issue by LukasPrism** [ironmonk88/monks-tokenbar#359]
In 5E you set a tokenbar stat to a resource (eg. resources.primary) and then deplete the resource to zero, on the tokenbar the value and the icon both vanish. Updating the resource to a positive value restores it. 

Very likely a core/dnd5e issue but one that MTB should be able to circumvent by displaying the value as 0 or - if null. Might make the tokenbar more robust in general.

Thanks!

**Comment by ironmonk88** [comment]
That's not really bug.  At least not with MTB.
The DnD5e character sheet sets the value and max to undefined if either of those values are 0;
![image](https://user-images.githubusercontent.com/75920956/233862042-eeb1a554-abc2-4fcf-bb6c-5bea3e30c58e.png)
It should probably be changed to set the value to undefined only if the max value is also undefined.
![image](https://user-images.githubusercontent.com/75920956/233862142-cabe246a-c8f0-4151-b888-b8047ffc2e08.png)

In the meantime, this was done on purpose for MTB so that tokens with a resource defined could be shown, but those without that resource would be hidden to indicate that they did not have that resource available.
I've added a setting so that you can force MTB to always show that stat.

You can also use `'{{resources.secondary.value}}' || 0` as your stat to make sure it appears.

**Comment by LukasPrism** [comment]
Makes perfect sense, thanks for sorting it Monk. I would have been fine with the stat formula but you've gone above and beyond as usual!!

**Comment by ironmonk88** [comment]
Setting has been added to the latest release, and an alternative provided.  :-)
