### ISSUE TITLE
Conflict with Monk's Tokenbar and Elevated Vision

### ISSUE THREAD

**Issue by FreshnessDND** [ironmonk88/monks-tokenbar#362]
Conflict with Monk's Tokenbar and EV.

Steps to Reproduce Errors...

1. Enable module EV and Monk's Tokenbar
2. Click map that has 'zero' EV settings or has never been preconfigured before.
3. Conversion workflow (webgl shadows)
4. Attempts to load scene
5. Error (1)
6. Scene will not transition. All tokens on canvas perceived to be 'deleted'
7. Attempt to force load scene. Fails
8. Error (2)
9. Won't reload previous or other scenes.
10. Refresh.

Issue is present for others as well and will continue to happen until the scene is configured for EV. However, I have observed the errors when imported maps with EV already configured.

Now, we have other modules Drag Ruler, About Face listed but they are simply caught in the crossfire imo.

This is posted on EV's page as well.

(1)
![image](https://github.com/caewok/fvtt-elevated-vision/assets/96202375/c0e064cf-aecc-4d53-a178-53115e8606a2)

(2)
![image](https://github.com/caewok/fvtt-elevated-vision/assets/96202375/cda83694-5195-4b10-b236-152349ccef12)

**Comment by ironmonk88** [comment]
This gets flagged a lot for Tokenbar because it uses the sceneView to check on tokens.
And all it does at that point is just collect information, it doesn't change anything.
So, pretty sure this was just getting caught in the cross fire as well.
Moot point though, I moved the refresh function to a proper Hook.
