### ISSUE TITLE
Add support for other ways to distribute xp

### ISSUE THREAD

**Issue by xdy** [ironmonk88/monks-tokenbar#61]
See https://github.com/xdy-forks/monks-tokenbar/commit/1e31ab43070bfc116a54238409708cf0ecd11db8 for an example.

The purpose of the 'Robin Hood' xp distribution method added in the above commit is to make the group's level converge quickly after they've diverged, without having to do individual adventures, just leveling up the lower leveled characters, stopping the higher leveled ones from gaining xp, remembering to add/subtract xp manually, etc.

If you think it seems useful I'll make a pull request. If not I'll just maintain my fork. :)

**Comment by ironmonk88** [comment]
I would totally be good with that.
Four changes though:

- I'd much prefer the choices be text rather than 0-3, like 'split', 'even', 'robinhood', 'nottingham'.  Just makes it easier to debug.  And consistent with the rest of the code.
- settings.js line 1504, make sure that's defaulting to 'split' and 'even' rather than true and false
- assignxp.html,  change the checkbox to a dropdown, defaulted to whatever to default choice is.
- Make sure the text in the drop down isn't super huge.

**Comment by xdy** [comment]
Sure thing. I'll take a look at that and try to get a PR in tomorrow.
The reason I went with numbers was so I could abuse js truthy/falsy so as to make minimal changes. It did feel kind of dirty. :)

**Comment by xdy** [comment]
Or tonight. :) 😴

**Comment by ironmonk88** [comment]
Lol.  Isn't that always the case.
Thank you for the code!
I've got it integrated and will release shortly.
