### ISSUE TITLE
[Bug] Owned Vehicles Appearing on TokenBar

### ISSUE THREAD

**Issue by aprusik** [ironmonk88/monks-tokenbar#63]
**Summary:**
Currently if there is a "Vehicle" type actor that is owned by a user it shows up on the TokenBar, with some issues, I'm assuming due to vehicles not having passive perception:
![image](https://user-images.githubusercontent.com/29558544/112065754-9c818f80-8b3b-11eb-93d3-5535bd15b79e.png)

**Steps to Reproduce:**
1. Create a Vehicle Actor
2. Configure Permissions on the new Vehicle to give any user ownership permissions
3. Place the Vehicle on a map

**Current Behavior:**
The Vehicle appears on the TokenBar and attempts to display passive perception but displays an unkeyed value.

**Expected Behavior:**
The Vehicle does not appear on the TokenBar.

**Comment by ironmonk88** [comment]
The values should be cleaned up now.

Although the vehicle will still appear on the list.  I have it set to exclude NPC's but include anything else due to needing familiars to show up on the list.  And the problem with setting specific things to look for is it's not consistent across systems.  So in order to display all the things that need to be displayed I end up displaying more than needs to be displayed.  
The downside of trying to make it universal.

**Comment by aprusik** [comment]
No problem! That gets rid of the major issue for me, and I appreciate your thoughtfulness to include families.
