### ISSUE TITLE
[Suggestion] Compatability with Tormenta 20

### ISSUE THREAD

**Issue by Priderino** [ironmonk88/monks-tokenbar#78]
I love the utility brought by this module and use it in all my DnD 5e games, but now I'm starting a campaign on Tormenta 20, a brazillian medieval game, and would love to have support for it. Some features work normally, but not all of them. Since the system is in portuguese, I'd be glad to help with any info or translation necessary.

**Comment by ironmonk88** [comment]
There's a some big changes coming that might fix this issue already.
But what is it currently missing, so I know what to look in to.

**Comment by Priderino** [comment]
The token viewer doesn't show any token, so I can't see their Defense, HP and MP. Basically, the party viewer doesn't work.

**Comment by ironmonk88** [comment]
Are the tokens "Owned" by a player?  It's working on my machine.  But it won't show any token not owned by a player.

**Comment by Priderino** [comment]
Well, I'm stupid, they weren't. I guess the only compatibility would be removing the eye for Passive Perception, since T20 doesn't have that, but that's not really a problem.

**Comment by ironmonk88** [comment]
Hey, no worries.
I wasn't sure what to use for the second attribute.  I went with perception because I figured someone might use it.
It can be removed in the settings though.
I'm going to close the ticket, since the original issue is solved, but let me know in a comment if there's a different attribute that should be the default in Tormenta 20.
