### ISSUE TITLE
Recommendation to add player owned NPCs

### ISSUE THREAD

**Issue by ditzer252** [ironmonk88/monks-tokenbar#80]
Would it be possible to include player owned NPCs (like sidekicks) in the Token Bar?
Great module - thanks!

**Comment by ironmonk88** [comment]
NPC's were generally left off because of lootables.  When you convert an NPC to lootable it gives players owner access to it, to grab items etc.  And I didn't want those NPC's to suddenly appear on the list once they were defeated.
That being said... if the NPC is friendly and controlled it should probably appear on the list.
Changes are in the latest release.
